#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "workout-tracker"
name = "Workout Tracker"
description.en = "A workout tracking web application for personal use (or family, friends) geared towards running and other GPX-based activities"

version = "0.15.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
code = "https://github.com/jovandeginste/workout-tracker"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/jovandeginste/workout-tracker/releases/download/v0.15.0/workout-tracker-v0.15.0-linux-amd64.tar.gz"
    amd64.sha256 = "8b05f0b1c32e081ce7461841602e3864ca4b53dc77029d4f0716bfe221f851ca"
    
    arm64.url = "https://github.com/jovandeginste/workout-tracker/releases/download/v0.15.0/workout-tracker-v0.15.0-linux-arm64.tar.gz"
    arm64.sha256 = "a734dc40f09d66d5858602dbb60b1b4919d1aa6cee8315d35695969c06dcef5f"
    
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.gz"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8080



