#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "workout-tracker"
name = "workout-tracker"
description.en = "A workout tracking web application for personal use (or family, friends) geared towards running and other GPX-based activities"

version = "0.14.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
code = "https://github.com/jovandeginste/workout-tracker"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/jovandeginste/workout-tracker/releases/download/v0.14.0/workout-tracker-v0.14.0-linux-amd64.tar.gz"
    amd64.sha256 = "53222a52f78a4196765dc248eb916d9aba181346bcd106f0fd48f20355b937eb"
    
    arm64.url = "https://github.com/jovandeginste/workout-tracker/releases/download/v0.14.0/workout-tracker-v0.14.0-linux-arm64.tar.gz"
    arm64.sha256 = "efd7bb508471e8f581a43d62a92a6e6a2e32a880e40019cce11d072bb0a643a1"
    
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.gz"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8080



