#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "workout-tracker"
name = "workout-tracker"
description.en = "A workout tracking web application for personal use (or family, friends) geared towards running and other GPX-based activities"

version = "0.11.5~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
code = "https://github.com/jovandeginste/workout-tracker"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/jovandeginste/workout-tracker/releases/download/v0.11.5/workout-tracker-v0.11.5-linux-amd64.tar.gz"
    amd64.sha256 = "b02e4479fe8f9e4b1534084643bf1ebb68e0162f5c64a5f7f9824684294bf4c8"
    
    arm64.url = "https://github.com/jovandeginste/workout-tracker/releases/download/v0.11.5/workout-tracker-v0.11.5-linux-arm64.tar.gz"
    arm64.sha256 = "fe8fe7c021c926aab3de8c497319578eb222c5e15030f33a7fcb4e1e4f61c93c"
    
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.gz"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8080



