#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "workout-tracker"
name = "workout-tracker"
description.en = "A workout tracking web application for personal use (or family, friends) geared towards running and other GPX-based activities"

version = "0.12.2~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
code = "https://github.com/jovandeginste/workout-tracker"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/jovandeginste/workout-tracker/releases/download/v0.12.2/workout-tracker-v0.12.2-linux-amd64.tar.gz"
    amd64.sha256 = "e9411bc6428859a520d60f5a8d8a6eb1216c42d452aef0b4365ade3ddd5f99c2"
    
    arm64.url = "https://github.com/jovandeginste/workout-tracker/releases/download/v0.12.2/workout-tracker-v0.12.2-linux-arm64.tar.gz"
    arm64.sha256 = "1052994cc55c877308ae8bfc9ade934a0e6c5dfdfb48d2d8a537d7d64c8dfc22"
    
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*linux-amd64.tar.gz"
    autoupdate.asset.arm64 = ".*linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8080



